const STOCKS_DB = [
  {
    id: Math.random(),
    name: 'APL',
    price: 500,
    status: 'red',
    percent: .03,
  },
  {
    id: Math.random(),
    name: 'GGL',
    price: 300,
    status: 'green',
    percent: 12,
  },
  {
    id: Math.random(),
    name: 'AMZ',
    price: 2000,
    status: 'green',
    percent: 5,
  },
  {
    id: Math.random(),
    name: 'APL',
    price: 500,
    status: 'red',
    percent: .03,
  },
  {
    id: Math.random(),
    name: 'GGL',
    price: 300,
    status: 'red',
    percent: 12,
  },
  {
    id: Math.random(),
    name: 'AMZ',
    price: 2000,
    status: 'red',
    percent: 5,
  },
  {
    id: Math.random(),
    name: 'APL',
    price: 500,
    status: 'red',
    percent: .03,
  },
  {
    id: Math.random(),
    name: 'GGL',
    price: 300,
    status: 'green',
    percent: 12,
  },
  {
    id: Math.random(),
    name: 'AMZ',
    price: 2000,
    status: 'green',
    percent: 5,
  },
  {
    id: Math.random(),
    name: 'APL',
    price: 500,
    status: 'red',
    percent: .03,
  },
  {
    id: Math.random(),
    name: 'GGL',
    price: 300,
    status: 'green',
    percent: 12,
  },
  {
    id: Math.random(),
    name: 'AMZ',
    price: 2000,
    status: 'green',
    percent: 5,
  },
  {
    id: Math.random(),
    name: 'APL',
    price: 500,
    status: 'red',
    percent: .03,
  },
  {
    id: Math.random(),
    name: 'GGL',
    price: 300,
    status: 'red',
    percent: 12,
  },
  {
    id: Math.random(),
    name: 'AMZ',
    price: 2000,
    status: 'red',
    percent: 5,
  },
  {
    id: Math.random(),
    name: 'APL',
    price: 500,
    status: 'red',
    percent: .03,
  },
  {
    id: Math.random(),
    name: 'GGL',
    price: 300,
    status: 'red',
    percent: 12,
  },
  {
    id: Math.random(),
    name: 'AMZ',
    price: 2000,
    status: 'red',
    percent: 5,
  },
  {
    id: Math.random(),
    name: 'APL',
    price: 500,
    status: 'red',
    percent: .03,
  },
  {
    id: Math.random(),
    name: 'GGL',
    price: 300,
    status: 'green',
    percent: 12,
  },
  {
    id: Math.random(),
    name: 'AMZ',
    price: 2000,
    status: 'green',
    percent: 5,
  },
  {
    id: Math.random(),
    name: 'APL',
    price: 500,
    status: 'red',
    percent: .03,
  },
  {
    id: 11,
    name: 'GGL',
    price: 300,
    status: 'green',
    percent: 12,
  },
 
]